deployment:
  tasks:
    - export DEPLOYPATH=/home/teraar1q/public_html/
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp *.pdf $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp w3layouts-License.txt $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH/css
    - /bin/cp -R fonts $DEPLOYPATH/fonts
    - /bin/cp -R images $DEPLOYPATH/images
    - /bin/cp -R js $DEPLOYPATH/js
